language: java
cache:
  directories:
    - $HOME/.m2
jdk: oraclejdk8
sudo: false
install:
  - chmod +x .travis/install-mariadb.sh
  - sudo .travis/install-mariadb.sh
before_script: mysql -uroot < src/test/resources/schema.sql
script: mvn -Dspring.datasource.password= verify
