language: java
before_cache:
- ./mvnw build-helper:remove-project-artifact
- find $HOME/.m2/ -type d -name '*-SNAPSHOT' -exec rm -rf {} \; 2>/dev/null
cache:
  directories:
    - $HOME/.m2
jdk: oraclejdk8
sudo: required
install: sudo -s source .travis/install-mariadb.sh
script: chmod +x mvnw && ./mvnw -Dspring.datasource.password= verify
after_success:
- bash <(curl -s https://codecov.io/bash)
